Created event for ScheduledTimeChanged and added snackbars based on that
FIRSTIsrael/lems pull request #897
Opened 2024-12-31 21:15 UTC by TheCommandCat

Closes #849

Hey, Apologies for the new PR - I accidentally deleted the branch while trying to upload the updated code, which caused the first PR to close.

Based on the feedback from @johnmeshulam, I've added a new event specific to schedule changes and included snackbars for the Field Manager and Judge Advisor when the event is emitted.

While working on this, I started wondering if it might be useful to include more context about the specific changes in the schedule (e.g., by passing data through the event and displaying it in the snackbars). Do you think this level of detail would be helpful for these roles, or is the current approach good enough?

2025-01-01 16:11 UTC, johnmeshulam requested changes
Much better, added some comments regarding standardization and usability,

2025-01-01 16:11 UTC, johnmeshulam commented on libs/types/src/lib/websocket.ts
> +  ScheduledTimeChanged: () => void;
Lets keep our conventions here: `camelCase` and not `PascalCase` for event names.
Also split into 2 events: `matchParticipantTeamUpdated` and `judgingSessionTeamUpdated`. In each event, transmit the session or match that was updated. For matches, also transmit the participant that was updated. This should give us a robust infrastructure we can reuse.

In any case - the schedule time of a match or session will not be changed. Just the team in that slot.

2025-01-01 16:11 UTC, johnmeshulam commented on apps/frontend/pages/lems/judge-advisor.tsx
> +      { name: 'ScheduledTimeChanged', handler: handleScheduleTimeChange }
only listen to `sessionTeamUpdated`

2025-01-01 16:11 UTC, johnmeshulam commented on apps/frontend/pages/lems/judge-advisor.tsx
> +    enqueueSnackbar('הלוז עודכן.', { variant: 'info' });
Please provide an informative message: `הקבוצה בסבב 2 חדר 3 אדום עודכנה`.

2025-01-01 16:11 UTC, johnmeshulam commented on apps/frontend/pages/lems/field-manager.tsx
> +      { name: 'ScheduledTimeChanged', handler: handleScheduleTimeChange },
Only listen to `matchParticipantTeamUpdated`

2025-01-01 16:11 UTC, johnmeshulam commented on apps/frontend/pages/lems/field-manager.tsx
> +  const handleScheduleTimeChange = (match: WithId<RobotGameMatch>) => {
Please provide an informative message: `הקבוצה במקצה 4 בשולחן 3 אדום עודכנה`

2025-01-01 16:11 UTC, johnmeshulam commented on apps/backend/src/websocket/handlers/field.ts
> +  const oldMatch = match;
Please use spread operation `{...match}`

2025-01-01 16:11 UTC, johnmeshulam commented on apps/backend/src/websocket/handlers/field.ts
> +  if (match.scheduledTime != oldMatch.scheduledTime)
At least one participant team has been updated. Emit an event for every participant team that was updated. No if statement needed

2025-01-01 16:11 UTC, johnmeshulam commented on apps/backend/src/websocket/handlers/judging.ts
> +  if (session.scheduledTime !== oldSession.scheduledTime)
This event updated the session team. No if statement needed - always emit that the team was updated.

2025-01-02 16:03 UTC, TheCommandCat commented
Should the judge-advisor also receive an informational message instead of just 'הלוז עודכן'? If so, what format should the message be? @johnmeshulam

2025-01-02 17:30 UTC, johnmeshulam commented
Please see my previous comments. As I mentioned, the schedules time does not change

2025-01-02 18:03 UTC, TheCommandCat commented
Im really sorry about all the mess...


I'm not entirely sure I understood your last comment. As I understand it, the schedule itself remains unchanged, and only the assigned teams are updated. Based on your advice, I renamed the events to more appropriate names. Is the issue with the specific message 'הלוז עודכן'? Should I update it to something like 'הקבוצה בסשן השיפוט בשעה {time} עודכנה' instead?

If yes, should i pass the updated JudgingSession object in the judgingSessionTeamUpdated event as well like I did previously with the field manager to get the JudgingSession info for the snackbar?

2025-01-02 20:37 UTC, johnmeshulam commented
The logic will not work as it's written right now. It seems like you understood eerything correctly but the logic itself is flawed, if I'll have time l'll leave more detailed comments later

2025-01-31 17:30 UTC, johnmeshulam commented
Backlogging this for now, feel free to open another PR after the competition season

2025-01-31 17:31 UTC, closed without merging